#
# $Name: REL_2_1_1 $
#
# $TAHI: ct/default-addr-select/Makefile.test,v 1.1 2002/09/25 12:07:24 kenta Exp $
#

PERL	= /usr/bin/perl
POD2HTML= -$(PERL) -e 'use Pod::Html; pod2html("--noindex", @ARGV);'

document:
	$(AUTORUN) -g INDEX
	$(POD2HTML) ADDR_SELECT.pm > ADDR_SELECT.html
	rm -f pod2html-dircache pod2html-itemcache

clean:
	-/bin/rm -f *.log *.dump [0-9]*.html index.html ID.def summary.html report.html

test:
	$(AUTORUN) $(AROPT) \
	-title='IPv6 Conformance Test For "Default Address Selection for IPv6"' \
	INDEX

tahi:	document
	/bin/rm -f index.html summary.html report.html
	$(AUTORUN) $(AROPT) -dump2txt \
	-title='IPv6 Conformance Test For "Default Address Selection for IPv6"' \
	INDEX

tiny:
	$(AUTORUN) -tiny -nolcna INDEX
	$(POD2HTML) ADDR_SELECT.pm > ADDR_SELECT.html
	rm -f pod2html-dircache pod2html-itemcache

.include "../Makefile.inc"
