#
# $Name: REL_2_1_1 $
#
# $TAHI: ct/ipsec/Makefile.test,v 1.27 2003/05/05 15:53:17 ozoe Exp $
#

PERL	= /usr/bin/perl
POD2HTML= -$(PERL) -e 'use Pod::Html; pod2html("--noindex", @ARGV);'

check:
	$(AUTORUN) -t INDEX_host INDEX_router

document:
	$(AUTORUN) -g \
	INDEX_host INDEX_host_ah INDEX_host_esp INDEX_host_common \
	INDEX_router INDEX_router_ah INDEX_router_esp INDEX_router_common
	$(POD2HTML) IPSEC.pm > IPSEC.html
	rm -f pod2html-dircache pod2html-itemcache

document2:
	$(AUTORUN) -G \
	INDEX_host INDEX_host_ah INDEX_host_esp INDEX_host_common \
	INDEX_router INDEX_router_ah INDEX_router_esp INDEX_router_common
	$(POD2HTML) IPSEC.pm > IPSEC.html
	rm -f pod2html-dircache pod2html-itemcache

clean:
	-/bin/rm -f *.log *.dump [0-9]*.html index.html summary.html report.html

test:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec' \
	INDEX_host INDEX_host_ah INDEX_host_esp INDEX_host_common \
	INDEX_router INDEX_router_ah INDEX_router_esp INDEX_router_common

test-host:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (Host)' \
	INDEX_host INDEX_host_ah INDEX_host_esp INDEX_host_common

test-router:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (Router)' \
	INDEX_router INDEX_router_ah INDEX_router_esp INDEX_router_common

tahi:	document
	/bin/rm -f index.html summary.html report.html
	$(AUTORUN) $(AROPT) -dump2txt \
	-title='IPv6 Conformance Test For IPv6 IPsec' \
	INDEX_host INDEX_host_ah INDEX_host_esp INDEX_host_common \
	INDEX_router INDEX_router_ah INDEX_router_esp INDEX_router_common

tiny:	document
	/bin/rm -f index.html summary.html report.html
	$(AUTORUN) $(AROPT) -dump2txt -tiny\
	-title='IPv6 Conformance Test For IPv6 IPsec' \
	INDEX_host INDEX_host_ah INDEX_host_esp INDEX_host_common INDEX_host_granularity

test-ah:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (AH)' \
	INDEX_host INDEX_host_ah \
	INDEX_router INDEX_router_ah

test-host-ah:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (Host AH)' \
	INDEX_host INDEX_host_ah

test-router-ah:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (Router AH)' \
	INDEX_router INDEX_router_ah

test-esp:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (ESP)' \
	INDEX_host INDEX_host_esp \
	INDEX_router INDEX_router_esp

test-host-esp:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (Host ESP)' \
	INDEX_host INDEX_host_esp

test-router-esp:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (Router ESP)' \
	INDEX_router INDEX_router_esp

test-common:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (Common)' \
	INDEX_host INDEX_host_common \
	INDEX_router INDEX_router_common

test-granularity:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (Granularity)' \
	INDEX_host_granularity

test-host-common:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (Host Common)' \
	INDEX_host INDEX_host_common

test-router-common:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec (Router Common)' \
	INDEX_router INDEX_router_common

demo:
	$(AUTORUN) $(AROPT)\
	-title='IPv6 Conformance Test For IPv6 IPsec demonstration ' \
	INDEX_demo

.include "../Makefile.inc"

