#
# Copyright (C) 2003 Yokogawa Electric Corporation, 
# INTAP(Interoperability Technology Association
# for Information Processing, Japan).  All rights reserved.
# 
# Redistribution and use of this software in source and binary forms, with 
# or without modification, are permitted provided that the following 
# conditions and disclaimer are agreed and accepted by the user:
# 
# 1. Redistributions of source code must retain the above copyright 
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright 
# notice, this list of conditions and the following disclaimer in the 
# documentation and/or other materials provided with the distribution.
# 
# 3. Neither the names of the copyrighters, the name of the project which 
# is related to this software (hereinafter referred to as "project") nor 
# the names of the contributors may be used to endorse or promote products 
# derived from this software without specific prior written permission.
# 
# 4. No merchantable use may be permitted without prior written 
# notification to the copyrighters. However, using this software for the 
# purpose of testing or evaluating any products including merchantable 
# products may be permitted without any notification to the copyrighters.
# 
# 
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHTERS, THE PROJECT AND 
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING 
# BUT NOT LIMITED THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE, ARE DISCLAIMED.  IN NO EVENT SHALL THE 
# COPYRIGHTERS, THE PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT,STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
# THE POSSIBILITY OF SUCH DAMAGE.
#
# $TAHI: ct/router-select/Makefile.test,v 1.8 2003/06/05 04:11:02 akisada Exp $
#

PERL	= /usr/bin/perl
POD2HTML= -$(PERL) -e 'use Pod::Html; pod2html("--noindex", @ARGV);'

NOPT=
DUMP2TXT= -dump2txt
IFILES  =  INDEX_HOST
#IFILES  =  INDEX_DEF

all:

document:
	/bin/rm -f *.html
	/bin/rm -f pod2html-dircache pod2html-itemcache
	$(AUTORUN) -g $(IFILES)

clean:
	/bin/rm -f *.log *.dump [0-9]*.html report.html summary.html index.html

test:
	$(AUTORUN) $(AROPT) \
	-title='IPv6 Conformance Test For Default Router Selection' \
	$(IFILES)

tahi:	document
	/bin/rm -f index.html summary.html report.html
	$(AUTORUN) $(AROPT) \
	-title='IPv6 Conformance Test For Default Router Selection ' \
	$(IFILES)

tiny:	document
	/bin/rm -f index.html summary.html report.html
	$(AUTORUN) $(AROPT) -tiny \
	-title='IPv6 Conformance Test For Default Router Selection ' \
	$(IFILES)


.include "../Makefile.inc"
